---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: microservices-demo
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/GoogleCloudPlatform/microservices-demo
  ref:
    branch: main
  ignore: |
    /*
    !/kustomize