apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: ingress-controller
spec:
  type: oci
  url: oci://ghcr.io/nginxinc/charts
  interval: 5m0s