apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-hotrod
  namespace: hotrod
  labels:
    app: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        ports:
        - containerPort: 8080
          name: frontend
          protocol: TCP
        - containerPort: 8081
          name: customer
          protocol: TCP
        - containerPort: 8082
          name: driver
          protocol: TCP
        - containerPort: 8083
          name: route
          protocol: TCP
        
        env:
        # Отправляем в Alloy 
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.alloy.svc.cluster.local:4318"
        
        # Указываем протокол (http/protobuf)
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        
        # Имя сервиса для трейсов
        - name: OTEL_SERVICE_NAME
          value: "hotrod"
        
        # Дополнительные атрибуты
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=hotrod,deployment.environment=production"
        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        
        args: ["all"]
        
        # Проверки здоровья
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: hotrod
spec:
  selector:
    app: hotrod
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
