apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  chart:
    spec:
      chart: loki
      version: 6.49.x
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 1h
  interval: 1h
  releaseName: loki
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true

      storage:
        type: filesystem 
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules

    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path

    # Отключаем MinIO - не нужен для filesystem storage
    minio:
      enabled: false

    # Минимальные ресурсы для gateway
    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    # Минимальные ресурсы для canary
    monitoring:
      lokiCanary:
        enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
