apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: online-boutique
  path: /
  targetNamespace: online-boutique
  