apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  interval: 5m
  url: https://gitlab.eqlan.ru/fill/online-boutique.git
  ref:
    branch: main